### ISSUE TITLE
can't connect awarness api

### ISSUE THREAD

**Issue by halukmy** [jamesmontemagno/XamarinAwareness#2] opened 2017-03-20 13:57 UTC
client = await new GoogleApiClient.Builder(this)
                .AddApi(Awareness.Api)
                .AddConnectionCallbacks(() =>
                {
                    text.Text = "Connected";
                })
                .BuildAndConnectAsync((i) =>
                {
                });
            

i checked some but can not get client ,

can you check too James?

**Comment by halukmy** [comment] 2017-04-04 14:18
@redth & @jamesmontemagno  any update?

**Comment by Redth** [comment] 2017-04-04 14:20
Please try and use `.Build ()` on the builder, and `.Connect()` on the resulting API Client, and implement the API that way instead of `.BuildAndConnectAsync ()` for now.  There may be an issue with `.BuildAndConnectAsync ()` which is something I'm investigating...

**Comment by halukmy** [comment] 2017-04-04 16:20
var _clientc = new GoogleApiClient.Builder(this).AddApi(Awareness.Api).Build();
                  _clientc.Connect();

                  Toast.MakeText(this, _clientc.IsConnected.ToString(), ToastLength.Long).Show();

i made this @Redth  but still with problem

did i use sytnax right?

**Comment by Redth** [comment] 2017-04-04 16:40
No, more like this:

```csharp
public class MainActivity : AppCompatActivity, GoogleApiClient.IConnectionCallbacks, GoogleApiClient.IOnConnectionFailedListener
{
	GoogleApiClient googleApiClient;

	protected override void OnCreate(Bundle savedInstanceState)
	{
		base.OnCreate(savedInstanceState);

		// Set our view from the "main" layout resource
		SetContentView(Resource.Layout.Main);

		googleApiClient = new GoogleApiClient.Builder(this)
			.AddConnectionCallbacks(this)
			.AddOnConnectionFailedListener(this)
			.AddApi(Awareness.Api)
			.Build();

		googleApiClient.Connect();
	}

	public void OnConnected(Bundle connectionHint)
	{
		Toast.MakeText(this, $"Connected: {googleApiClient.IsConnected}", ToastLength.Long).Show();
	}

	public void OnConnectionFailed(ConnectionResult result)
	{
		Toast.MakeText(this, "Connection Failed!", ToastLength.Long).Show();
	}

	public void OnConnectionSuspended(int cause)
	{
		Toast.MakeText(this, "Connection Suspended!", ToastLength.Long).Show();
	}
}
```

**Comment by halukmy** [comment] 2017-04-04 18:22
sadly i get this An unhandled exception occured.

**Comment by Redth** [comment] 2017-04-04 18:39
Going to need more info...  Stack traces, etc.

**Comment by halukmy** [comment] 2017-04-04 18:52
my vs17 get lose itself,  

@Redth 

after     googleApiClient.Connect(); row,

unable to manage try catch blog

just outline is https://jpst.it/WQmD

can you share working awareness sample  ?

**Comment by halukmy** [comment] 2017-04-05 14:18
@Redth  any update or any working awareness api?

im planing to run xamarin smart app in smart city applications i need to hurry about it

**Comment by Redth** [comment] 2017-04-11 13:47
I can't reproduce any issues here.  I think @jamesmontemagno should close this issue.  We were already tracking this issue here: https://github.com/xamarin/GooglePlayServicesComponents/issues/51

I've closed the original issue as well since I can't reproduce the issue and nobody has provided any more information about how to do so given the code I've provided.

Thanks

**Closed as completed** 2017-04-11 16:57 UTC
